[package]
name = "smb-io-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
smb-io-wire = { path = "../smb-wire" }
smb-io-client = { path = "../smb-client" }
smb-io-auth = { path = "../smb-auth" }

[dev-dependencies]
tokio = { version = "1.40", features = ["macros", "rt"] }

[lints]
workspace = true
