[package]
name = "smb-io-android"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
smb-io-auth = { path = "../smb-auth" }
smb-io-client = { path = "../smb-client" }
smb-io-fs = { path = "../smb-fs" }
smb-io-stream = { path = "../smb-stream" }
getrandom = "0.3"
jni = "0.22"
tokio = { version = "1.40", features = ["rt-multi-thread", "time", "net"] }
zeroize = "1.8"

[lints.clippy]
all = "warn"
